In [2]:
import numpy as np
arr1 =np.array([1,2,3])
print (arr1)

[1 2 3]


In [2]:
import numpy as np
arr1 =np.array([1,2,3])
print (arr1)

[1 2 3]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(3,)


In [7]:
print(arr1[2])

3


In [10]:
arr1[2]=5
arr1

array([1, 2, 5])

In [14]:
arr2 =np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [22]:
arr2[1]

array([3, 4, 5])

In [23]:
arr2[1][2]

5

In [24]:
print(arr2.shape)

(2, 3)


In [25]:
arr2[1,2]

5

In [26]:
# arrs--->is for string arrays

arrs=np.array(['china','india','USA',"Mexico"])
arrs

array(['china', 'india', 'USA', 'Mexico'], dtype='<U6')

In [35]:
# arrR---> for range
arrR=np.arange(0,18,2)
arrR


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [36]:
# arrL----> for length

arrL=np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [42]:
arr=np.random.rand(20)
arr

array([0.65877493, 0.01457222, 0.13467586, 0.55968535, 0.73448405,
       0.51988239, 0.03210945, 0.62964013, 0.92884432, 0.86207891,
       0.6097454 , 0.581619  , 0.08181589, 0.81784092, 0.76942766,
       0.46833454, 0.64606275, 0.87499367, 0.6007096 , 0.04179169])

In [40]:
#(3,4) is row and column
arr=np.random.rand(3,4)
arr
        


array([[6.83026031e-01, 7.43703349e-04, 1.63441243e-01, 5.33752229e-02],
       [2.02220591e-01, 2.26501222e-02, 8.74122318e-01, 3.21973311e-01],
       [9.86226227e-02, 9.35569202e-01, 8.95057839e-01, 9.89179653e-01]])

In [41]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [49]:
print(np.ones((4,5,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [50]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [54]:

print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [66]:
identity_matrix=np.eye(3)
                      
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [72]:
arr=np.random.rand(5,5)
arr

array([[0.6664145 , 0.07093066, 0.80450077, 0.55788958, 0.55085367],
       [0.08164466, 0.7282787 , 0.25749942, 0.22746267, 0.15722388],
       [0.50814875, 0.3491142 , 0.29999766, 0.63873097, 0.03125504],
       [0.40053259, 0.21796744, 0.58202595, 0.45574698, 0.89683082],
       [0.59829522, 0.3623735 , 0.42559913, 0.1284215 , 0.0099443 ]])

In [73]:
np.diag(arr)

array([0.6664145 , 0.7282787 , 0.29999766, 0.45574698, 0.0099443 ])

In [74]:
arr.ndim

2

In [75]:
arr.size

25

In [76]:
arr.shape


(5, 5)

In [88]:
np.random.randint(-5,5,4)

array([ 1,  3, -4, -3])

In [87]:
arr+10

array([[10.6664145 , 10.07093066, 10.80450077, 10.55788958, 10.55085367],
       [10.08164466, 10.7282787 , 10.25749942, 10.22746267, 10.15722388],
       [10.50814875, 10.3491142 , 10.29999766, 10.63873097, 10.03125504],
       [10.40053259, 10.21796744, 10.58202595, 10.45574698, 10.89683082],
       [10.59829522, 10.3623735 , 10.42559913, 10.1284215 , 10.0099443 ]])

In [92]:
#exponential function
np.exp(arr)

array([[1.94724294, 1.07350678, 2.23558014, 1.74698174, 1.73473327],
       [1.08507017, 2.07151185, 1.29369107, 1.25541058, 1.17025759],
       [1.66221117, 1.4178111 , 1.34985565, 1.89407572, 1.03174861],
       [1.49261943, 1.24354658, 1.78966053, 1.57735119, 2.45182053],
       [1.81901514, 1.43673546, 1.53050711, 1.13703216, 1.0099939 ]])

In [94]:
arr

array([[0.6664145 , 0.07093066, 0.80450077, 0.55788958, 0.55085367],
       [0.08164466, 0.7282787 , 0.25749942, 0.22746267, 0.15722388],
       [0.50814875, 0.3491142 , 0.29999766, 0.63873097, 0.03125504],
       [0.40053259, 0.21796744, 0.58202595, 0.45574698, 0.89683082],
       [0.59829522, 0.3623735 , 0.42559913, 0.1284215 , 0.0099443 ]])

In [96]:
np.log2(arr)

array([[-0.58550831, -3.81744691, -0.3138343 , -0.84194849, -0.86025898],
       [-3.61449767, -0.45743744, -1.95735889, -2.13629829, -2.6691077 ],
       [-0.97667722, -1.51822904, -1.73697686, -0.64671968, -4.99976724],
       [-1.32000848, -2.19781545, -0.78084461, -1.133695  , -0.15709224],
       [-0.74107055, -1.46445065, -1.23243291, -2.96104138, -6.65191502]])

In [97]:
#u can do all trignometric functions
np.sin(arr)

array([[0.61817161, 0.07087119, 0.72048453, 0.52939695, 0.52341481],
       [0.08155398, 0.66558598, 0.25466322, 0.22550628, 0.15657694],
       [0.48656074, 0.34206558, 0.29551797, 0.59617708, 0.03124995],
       [0.38990883, 0.2162456 , 0.54971744, 0.44013317, 0.78135299],
       [0.56323464, 0.35449459, 0.41286653, 0.1280688 , 0.00994413]])

In [98]:
arr

array([[0.6664145 , 0.07093066, 0.80450077, 0.55788958, 0.55085367],
       [0.08164466, 0.7282787 , 0.25749942, 0.22746267, 0.15722388],
       [0.50814875, 0.3491142 , 0.29999766, 0.63873097, 0.03125504],
       [0.40053259, 0.21796744, 0.58202595, 0.45574698, 0.89683082],
       [0.59829522, 0.3623735 , 0.42559913, 0.1284215 , 0.0099443 ]])

In [100]:
#adding all the values in array
np.sum(arr)

10.007682549056058

In [101]:
np.sum(arr,axis=0)

array([2.25503571, 1.7286645 , 2.36962293, 2.0082517 , 1.64610771])

In [103]:
np.min(arr,axis=0)

array([0.08164466, 0.07093066, 0.25749942, 0.1284215 , 0.0099443 ])

In [104]:
np.max(arr,axis=0)

array([0.6664145 , 0.7282787 , 0.80450077, 0.63873097, 0.89683082])

In [105]:
np.mean(arr,axis=0)

array([0.45100714, 0.3457329 , 0.47392459, 0.40165034, 0.32922154])

In [106]:
np.median(arr,axis=0)

array([0.50814875, 0.3491142 , 0.42559913, 0.45574698, 0.15722388])

In [107]:
#standard deviatio we can do axis wise or all together
np.std(arr,axis=0)

array([0.2051027 , 0.21838952, 0.20019605, 0.19418533, 0.34397857])

In [108]:
#variation or varients we can do axis wise or all together
np.var(arr,axis=0)

array([0.04206712, 0.04769398, 0.04007846, 0.03770794, 0.11832126])

In [110]:
arr

array([[0.6664145 , 0.07093066, 0.80450077, 0.55788958, 0.55085367],
       [0.08164466, 0.7282787 , 0.25749942, 0.22746267, 0.15722388],
       [0.50814875, 0.3491142 , 0.29999766, 0.63873097, 0.03125504],
       [0.40053259, 0.21796744, 0.58202595, 0.45574698, 0.89683082],
       [0.59829522, 0.3623735 , 0.42559913, 0.1284215 , 0.0099443 ]])

In [115]:
arr[2:,2:4]

array([[0.29999766, 0.63873097],
       [0.58202595, 0.45574698],
       [0.42559913, 0.1284215 ]])

In [117]:
np.sort(arr, axis=1)

array([[0.07093066, 0.55085367, 0.55788958, 0.6664145 , 0.80450077],
       [0.08164466, 0.15722388, 0.22746267, 0.25749942, 0.7282787 ],
       [0.03125504, 0.29999766, 0.3491142 , 0.50814875, 0.63873097],
       [0.21796744, 0.40053259, 0.45574698, 0.58202595, 0.89683082],
       [0.0099443 , 0.1284215 , 0.3623735 , 0.42559913, 0.59829522]])

In [118]:
#transpose-->.T or transpose() both are same
arr.T

array([[0.6664145 , 0.08164466, 0.50814875, 0.40053259, 0.59829522],
       [0.07093066, 0.7282787 , 0.3491142 , 0.21796744, 0.3623735 ],
       [0.80450077, 0.25749942, 0.29999766, 0.58202595, 0.42559913],
       [0.55788958, 0.22746267, 0.63873097, 0.45574698, 0.1284215 ],
       [0.55085367, 0.15722388, 0.03125504, 0.89683082, 0.0099443 ]])

In [120]:
#slicing
arr[:3,:].T

array([[0.6664145 , 0.08164466, 0.50814875],
       [0.07093066, 0.7282787 , 0.3491142 ],
       [0.80450077, 0.25749942, 0.29999766],
       [0.55788958, 0.22746267, 0.63873097],
       [0.55085367, 0.15722388, 0.03125504]])